---
version: '3.4'

services:
  nix:
    working_dir: "/usr/src/app"
    image: lnl7/nix:2.3.7
    command: ["/bin/sh"]
    volumes:
      - ".:/usr/src/app:cached"
  nix-ubuntu:
    working_dir: "/usr/src/app"
    build:
      context: "."
    command: ["/bin/bash"]
    volumes:
      - ".:/usr/src/app:cached"
