name: 'Nixpkgs'
env:
  ACTIONS_RUNNER_DEBUG: true
on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'cf-worker'
  push:
    branches-ignore:
      - 'gh-pages'
      - 'cf-worker'
  workflow_dispatch:
    branches-ignore:
      - 'gh-pages'
      - 'cf-worker'
    inputs:
      deploy:
        description: 'Deploy: [true, false]'
        type: boolean
        required: true
        default: false
      debug_timeout:
        description: 'Debug timeout'
        required: false
        default: 30
      tmate:
        description: 'Debug with tmate?'
        type: boolean
        required: false
        default: false

jobs:
  tests-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    steps:
    - uses: actions/checkout@v4

      # flakes and nix-command is enabled by default, to disable just set
      # extra_nix_config: |
      #   experimental-features =
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Print nix.conf
      run: cat /etc/nix/nix.conf

    - name: Build tests
      run: nix build -f tests.nix

    - name: Cleanup test results
      run: rm -rf results*

    - name: Create output path
      if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
      run: mkdir -p _output/cache

      # We only need to do this particular step once
    - name: Create channel archive
      if: startsWith(matrix.os,'ubuntu') && (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
      run: |
        tar -cJf "_output/nixexprs.tar.xz" ./*.nix pkgs/ maintainers/ \
            --transform "s,^,${PWD##*/}/," \
            --owner=0 --group=0 --mtime="1970-01-01 00:00:00 UTC"

        touch "_output/index.html"
        printf 'https://nixpkgs.raunco.co/cache' > "_output/binary-cache-url"

    - name: Build the packages
      if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
      run: nix build -f default.nix

    - name: Remove graalvm packages from cache, as they are already compiled binaries
      if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
      run: |
        nix store delete /nix/store/*graalvm-ce* || true
        nix store delete /nix/store/*installable*java* || true

    - name: optimize nix-store to reduce size
      if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
      run: nix store optimise

    - name: Sign the packages
      if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
      run: |
        export NIX_SECRET_KEY_FILE="$PWD/nix-cache-priv-key.pem"
        echo "$NIX_SECRET_KEY" > "$NIX_SECRET_KEY_FILE"
        nix store sign -f default.nix -k "$NIX_SECRET_KEY_FILE"
        rm -rf "$NIX_SECRET_KEY_FILE"
      env:
        NIX_SECRET_KEY: ${{ secrets.NIX_SECRET_KEY }}

    - name: Setup tmate session
      if: ${{ github.event.inputs.tmate }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: ${{ github.event.inputs.debug_timeout }}
      with:
        limit-access-to-actor: true

      # nix copy -f default.nix --to "file:///$PWD/_output/cache?compression=xz"
    - name: nix copy to file
      run: |
        nix copy -f default.nix --to "file://$PWD/_output/cache?compression=xz"

      # For some reason this command is failing.
      # https://github.com/cachix/install-nix-action/issues/60
    - name: nix path-info
      run: |
        nix path-info -f default.nix --store "file://$PWD/_output/cache" --json | json_pp || true

    - name: Upload artifacts
      if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: nix-cache-${{ matrix.os }}-${{ github.sha }}
        path: _output

  deploy:
    needs: "tests-and-build"
    if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Cleanup tasks
      run: |
        sudo apt clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      #v2.0.10
    - name: Download linux artifacts
      uses: actions/download-artifact@v3
      with:
        name: nix-cache-ubuntu-22.04-${{ github.sha }}
        path: nix-cache-ubuntu-22.04-${{ github.sha }}

      #v2.0.8
    - name: Download mac artifacts
      uses: actions/download-artifact@v3
      with:
        name: nix-cache-macos-12-${{ github.sha }}
        path: nix-cache-macos-12-${{ github.sha }}

    - name: Combine cache files
      run: |
        mkdir -p _output
        cp -r nix-cache-macos-12-${GITHUB_SHA}/. _output
        rm -rf nix-cache-macos-12-${GITHUB_SHA}/
        cp -r nix-cache-ubuntu-22.04-${GITHUB_SHA}/. _output
        rm -rf nix-cache-ubuntu-22.04-${GITHUB_SHA}/
        ls -lart -hu _output/
        du -hc _output/

      #v4.1.6
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        branch: gh-pages
        folder: _output
        clean: true
        clean-exclude: |
          .gitattributes
          CNAME
      env:
        #GIT_TRACE_PACKET: 1
        GIT_TRACE: 1
        #GIT_CURL_VERBOSE: 1
        GIT_CONFIG_COUNT: 7
        GIT_CONFIG_KEY_0: "http.postBuffer"
        GIT_CONFIG_VALUE_0: 104857600
        GIT_CONFIG_KEY_1: "lfs.dialtimeout"
        GIT_CONFIG_VALUE_1: 60
        GIT_CONFIG_KEY_2: "lfs.tlstimeout"
        GIT_CONFIG_VALUE_2: 60
        GIT_CONFIG_KEY_3: "lfs.activitytimeout"
        GIT_CONFIG_VALUE_3: 60
        GIT_CONFIG_KEY_4: "lfs.keepalive"
        GIT_CONFIG_VALUE_4: 60
        GIT_CONFIG_KEY_5: "lfs.transfer.maxretries"
        GIT_CONFIG_VALUE_5: 10
        GIT_CONFIG_KEY_6: "lfs.pruneverifyremotealways"
        GIT_CONFIG_VALUE_6: true

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

  test-channel:
    needs: "deploy"
    if: (github.event_name == 'push' || github.event.inputs.deploy) && github.ref == 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    steps:
    - uses: actions/checkout@v4

      # v16
      # flakes and nix-command is enabled by default, to disable just set
      # extra_nix_config: |
      #   experimental-features =
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Print nix.conf
      run: cat /etc/nix/nix.conf

    - name: Add channel
      run: |
        nix-channel --add https://nixpkgs.raunco.co/ raunco
        nix-channel --update
        nix-channel --list

    - name: Add cache to users nix config
      run: |
        mkdir  -p ~/.config/nix
        cat <<EOT >> ~/.config/nix/nix.conf
        substituters = https://cache.nixos.org https://nixpkgs.raunco.co/cache
        trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixpkgs.raunco.co:bb6Y8BB7fkbRlhaUFzbubClYT5OlHyqEmCG8uh9Kt2U=
        EOT
        cat ~/.config/nix/nix.conf

      # nix-shell -E 'with import <nixpkgs> { }; with import <raunco> {}; runCommand"dummy" { buildInputs = [ vaulted nodejs-8_x rapture ]; } ""'
    - name: Install some packages defined in raunco channel
      run: |
        nix-env -iA raunco.vaulted
        nix-env -iA raunco.rapture

    - name: Check that packages were actually installed
      run: |
        rapture version
        vaulted --version
        node --version
