name: "Nixpkgs"
on:
  pull_request:
    branches-ignore:
      - "gh-pages"
  push:
    branches-ignore:
      - "gh-pages"
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      # v2.1.0
    - uses: actions/checkout@01aecccf73
      # v8
    - uses: cachix/install-nix-action@ebed63b0a2
    - name: Print nix.conf
      run: cat /etc/nix/nix.conf
    - name: Build tests
      run: nix-build tests.nix

  # Only deploy when commit is merged or pushed to master
  build-nix-cache:
    needs: "tests"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      # v2.1.0
    - uses: actions/checkout@01aecccf73
      # v8
    - uses: cachix/install-nix-action@ebed63b0a2
    - name: Create output path
      run: mkdir -p _output/cache
      # We only need to do this particular step once
    - name: Create channel archive
      if: startsWith(matrix.os,'ubuntu')
      run: |
        tar -cJf "_output/nixexprs.tar.xz" ./*.nix \
            --transform "s,^,${PWD##*/}/," \
            --owner=0 --group=0 --mtime="1970-01-01 00:00:00 UTC"

        touch "_output/index.html"
        printf 'https://nixpkgs.raunco.co/cache' > "_output/binary-cache-url"
    - name: Build the packages
      run: nix-build
    - name: Sign the packages
      run: |
        nix sign-paths --key-file <(echo $NIX_SECRET_KEY)
        nix copy --to "file:///$PWD/_output/cache"
        nix path-info --store "file:///$PWD/_output/cache" --json | json_pp
      env:
        NIX_SECRET_KEY: ${{ secrets.NIX_SECRET_KEY }}
    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@1283ca12b6
      with:
        name: nix-cache-${{ matrix.os }}-${{ github.sha }}
        path: _output
  deploy:
    needs: "build-nix-cache"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      # v2.1.0
    - uses: actions/checkout@01aecccf73
      with:
        persist-credentials: false
    - name: Download linux artifacts
      uses: actions/download-artifact@b85295d276
      with:
        name: nix-cache-ubuntu-18.04-${{ github.sha }}
    - name: Download mac artifacts
      uses: actions/download-artifact@b85295d276
      with:
        name: nix-cache-macos-10.15-${{ github.sha }}
    - name: Combine cache files
      run: |
        mkdir -p _output
        cp -r nix-cache-macos-10.15-${GITHUB_SHA}/. _output
        cp -r nix-cache-ubuntu-18.04-${GITHUB_SHA}/. _output
    #- name: Upload combined artifacts
      #uses: actions/upload-artifact@v1
      #with:
        #name: nix-cache-combined-${{ github.sha }}
        #path: _output

      #v0.2.0
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@b6c65becb0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      #v3
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@f8bad71bf4
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: _output
        CLEAN: true
